# Generated by Django 2.2.16 on 2022-12-16 08:17

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Введите текст от 3-х до 140 символов', max_length=140, validators=[posts.validators.min_size], verbose_name='Текст комментария'),
        ),
    ]
