# Generated by Django 2.2.16 on 2022-12-19 19:07

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20221218_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Введите текст от 3-х до 140 символов', max_length=140, validators=[posts.validators.size_comment], verbose_name='Текст комментария'),
        ),
    ]
